version: 1
disable_existing_loggers: false
formatters:
  default:
    format: "%(asctime)s %(levelname).1s %(name)s:%(lineno)d - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout
loggers:
  uvicorn:
    level: INFO
  uvicorn.error:
    level: INFO
  uvicorn.access:
    handlers: [ console ]
    level: INFO
    propagate: false
  aiokafka:
    level: INFO
root:
  handlers: [ console ]
  level: INFO